### ISSUE TITLE
How to integrate `setuptools-scm`?

### ISSUE THREAD

**Issue by paddyroddy** [UCL-ARC/python-template#13]
Ideally, we'd have something like the following included in the `pyproject.toml`.

```toml
[build-system]
requires = [
    "setuptools-scm",
]

[project]
dynamic = [
    "version",
]

[tool.setuptools_scm]
```

This has the advantage that all files tracked by `git` are included in the build - avoiding the need for `MANIFEST.in` etc. Also, we can do dynamic versioning. 

If we have this, I run into issues as the templated generated code isn't a `git` repo. How can we get this to work nicely?
